../uvm_tb/loopback_uvm_interface.sv
../uvm_tb/loopback_uvm_pkg.sv
../src/basys3_hex4_mux.sv
../src/clk_div.sv
../src/digit_register_bank.sv
../src/i2c_master.sv
../src/i2c_reg_master.sv
../src/i2c_reg_slave.sv
../src/i2c_slave.sv
../src/sb_minimal_top.sv
../src/spi_master.sv
../src/spi_reg_master.sv
../src/spi_reg_slave.sv
../src/spi_slave.sv
../uvm_tb/tb_loopback_uvm.sv
