#ifndef SOC_ADDRESS_MAP_H
#define SOC_ADDRESS_MAP_H

#include "address_map.h"

#define TIMER_BASE        ADDR_TIMER_BASE
#define GPIOA_BASE        ADDR_GPIO_BASE
#define GPIOB_BASE        ADDR_GPIO_B_BASE
#define GPIOC_BASE        ADDR_GPIO_C_BASE
#define SPI_BASE          ADDR_SPI_BASE
#define I2C_BASE          ADDR_I2C_BASE
#define UART_BASE         ADDR_UART_BASE
#define DMA_BASE          ADDR_DMA_BASE
#define PLIC_BASE         ADDR_PLIC_BASE
#define ISRAM_BASE        ADDR_ISRAM_BASE
#define ISRAM_END         (ADDR_ISRAM_BASE + ADDR_ISRAM_SIZE)
#define DSRAM_BASE        ADDR_DSRAM_BASE
#define DSRAM_END         (ADDR_DSRAM_BASE + ADDR_DSRAM_SIZE)
#define SRAM_BASE         ADDR_DSRAM_BASE
#define SRAM_APP_BASE     ADDR_RAM_APP_BASE
#define SRAM_APP_END      (ADDR_RAM_APP_BASE + ADDR_RAM_APP_SIZE)
#define IMAGE_BASE        ADDR_IMAGE_STAGING_BASE
#define IMAGE_HEADER_SIZE ADDR_IMAGE_STAGING_HEADER_SIZE
#define IMAGE_SIZE        (ADDR_IMAGE_STAGING_SIZE - IMAGE_HEADER_SIZE)
#define IMAGE_PAYLOAD_BASE (IMAGE_BASE + IMAGE_HEADER_SIZE)
#define SRAM_END          DSRAM_END

#endif
