## Basys 3 / xc7a35tcpg236-1 constraints for SocFpgaTop.

set_property PACKAGE_PIN W5 [get_ports iClk100M]
set_property IOSTANDARD LVCMOS33 [get_ports iClk100M]
create_clock -period 10.000 -name iClk100M [get_ports iClk100M]
create_generated_clock -name wSocClk -source [get_ports iClk100M] -divide_by 2 [get_pins uSocClkBuf/O]

set_property PACKAGE_PIN U18 [get_ports iReset]
set_property IOSTANDARD LVCMOS33 [get_ports iReset]

## User buttons for GPIOC. BTN_C remains iReset.
set_property PACKAGE_PIN T18 [get_ports {iBtn[0]}]
set_property PACKAGE_PIN W19 [get_ports {iBtn[1]}]
set_property PACKAGE_PIN T17 [get_ports {iBtn[2]}]
set_property PACKAGE_PIN U17 [get_ports {iBtn[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {iBtn[*]}]

set_property PACKAGE_PIN V17 [get_ports {iSw[0]}]
set_property PACKAGE_PIN V16 [get_ports {iSw[1]}]
set_property PACKAGE_PIN W16 [get_ports {iSw[2]}]
set_property PACKAGE_PIN W17 [get_ports {iSw[3]}]
set_property PACKAGE_PIN W15 [get_ports {iSw[4]}]
set_property PACKAGE_PIN V15 [get_ports {iSw[5]}]
set_property PACKAGE_PIN W14 [get_ports {iSw[6]}]
set_property PACKAGE_PIN W13 [get_ports {iSw[7]}]
set_property PACKAGE_PIN V2  [get_ports {iSw[8]}]
set_property PACKAGE_PIN T3  [get_ports {iSw[9]}]
set_property PACKAGE_PIN T2  [get_ports {iSw[10]}]
set_property PACKAGE_PIN R3  [get_ports {iSw[11]}]
set_property PACKAGE_PIN W2  [get_ports {iSw[12]}]
set_property PACKAGE_PIN U1  [get_ports {iSw[13]}]
set_property PACKAGE_PIN T1  [get_ports {iSw[14]}]
set_property PACKAGE_PIN R2  [get_ports {iSw[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {iSw[*]}]

set_property PACKAGE_PIN U16 [get_ports {oLed[0]}]
set_property PACKAGE_PIN E19 [get_ports {oLed[1]}]
set_property PACKAGE_PIN U19 [get_ports {oLed[2]}]
set_property PACKAGE_PIN V19 [get_ports {oLed[3]}]
set_property PACKAGE_PIN W18 [get_ports {oLed[4]}]
set_property PACKAGE_PIN U15 [get_ports {oLed[5]}]
set_property PACKAGE_PIN U14 [get_ports {oLed[6]}]
set_property PACKAGE_PIN V14 [get_ports {oLed[7]}]
set_property PACKAGE_PIN V13 [get_ports {oLed[8]}]
set_property PACKAGE_PIN V3  [get_ports {oLed[9]}]
set_property PACKAGE_PIN W3  [get_ports {oLed[10]}]
set_property PACKAGE_PIN U3  [get_ports {oLed[11]}]
set_property PACKAGE_PIN P3  [get_ports {oLed[12]}]
set_property PACKAGE_PIN N3  [get_ports {oLed[13]}]
set_property PACKAGE_PIN P1  [get_ports {oLed[14]}]
set_property PACKAGE_PIN L1  [get_ports {oLed[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLed[*]}]

## PMOD JA/JB: GPIOB[15:0].
set_property PACKAGE_PIN J1  [get_ports {ioGpioB[0]}]
set_property PACKAGE_PIN L2  [get_ports {ioGpioB[1]}]
set_property PACKAGE_PIN J2  [get_ports {ioGpioB[2]}]
set_property PACKAGE_PIN G2  [get_ports {ioGpioB[3]}]
set_property PACKAGE_PIN H1  [get_ports {ioGpioB[4]}]
set_property PACKAGE_PIN K2  [get_ports {ioGpioB[5]}]
set_property PACKAGE_PIN H2  [get_ports {ioGpioB[6]}]
set_property PACKAGE_PIN G3  [get_ports {ioGpioB[7]}]
set_property PACKAGE_PIN A14 [get_ports {ioGpioB[8]}]
set_property PACKAGE_PIN A16 [get_ports {ioGpioB[9]}]
set_property PACKAGE_PIN B15 [get_ports {ioGpioB[10]}]
set_property PACKAGE_PIN B16 [get_ports {ioGpioB[11]}]
set_property PACKAGE_PIN A15 [get_ports {ioGpioB[12]}]
set_property PACKAGE_PIN A17 [get_ports {ioGpioB[13]}]
set_property PACKAGE_PIN C15 [get_ports {ioGpioB[14]}]
set_property PACKAGE_PIN C16 [get_ports {ioGpioB[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ioGpioB[*]}]

## PMOD JC: SPI.
set_property PACKAGE_PIN K17 [get_ports oSpiSclk]
set_property PACKAGE_PIN M18 [get_ports oSpiMosi]
set_property PACKAGE_PIN N17 [get_ports iSpiMiso]
set_property PACKAGE_PIN P18 [get_ports {oSpiCsN[0]}]
set_property PACKAGE_PIN L17 [get_ports {oSpiCsN[1]}]
set_property PACKAGE_PIN M19 [get_ports {oSpiCsN[2]}]
set_property PACKAGE_PIN P17 [get_ports {oSpiCsN[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oSpiSclk oSpiMosi iSpiMiso oSpiCsN[*]}]

## JXADC pins used as simple digital I2C header pins.
set_property PACKAGE_PIN J3 [get_ports ioI2cScl]
set_property PACKAGE_PIN L3 [get_ports ioI2cSda]
set_property IOSTANDARD LVCMOS33 [get_ports {ioI2cScl ioI2cSda}]
set_property PULLUP true [get_ports {ioI2cScl ioI2cSda}]

## USB-UART.
set_property PACKAGE_PIN B18 [get_ports iUartRx]
set_property PACKAGE_PIN A18 [get_ports oUartTx]
set_property IOSTANDARD LVCMOS33 [get_ports {iUartRx oUartTx}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
