## Basys 3 / xc7a35tcpg236-1 constraints for GpioSpiSlaveTop.
## Keep this XDC out of constrs/ while the master SocFpgaTop build is selected.

set_property PACKAGE_PIN W5 [get_ports iClk100M]
set_property IOSTANDARD LVCMOS33 [get_ports iClk100M]
create_clock -period 10.000 -name iClk100M [get_ports iClk100M]

set_property PACKAGE_PIN U18 [get_ports iReset]
set_property IOSTANDARD LVCMOS33 [get_ports iReset]

set_property PACKAGE_PIN V17 [get_ports {iSw[0]}]
set_property PACKAGE_PIN V16 [get_ports {iSw[1]}]
set_property PACKAGE_PIN W16 [get_ports {iSw[2]}]
set_property PACKAGE_PIN W17 [get_ports {iSw[3]}]
set_property PACKAGE_PIN W15 [get_ports {iSw[4]}]
set_property PACKAGE_PIN V15 [get_ports {iSw[5]}]
set_property PACKAGE_PIN W14 [get_ports {iSw[6]}]
set_property PACKAGE_PIN W13 [get_ports {iSw[7]}]
set_property PACKAGE_PIN V2  [get_ports {iSw[8]}]
set_property PACKAGE_PIN T3  [get_ports {iSw[9]}]
set_property PACKAGE_PIN T2  [get_ports {iSw[10]}]
set_property PACKAGE_PIN R3  [get_ports {iSw[11]}]
set_property PACKAGE_PIN W2  [get_ports {iSw[12]}]
set_property PACKAGE_PIN U1  [get_ports {iSw[13]}]
set_property PACKAGE_PIN T1  [get_ports {iSw[14]}]
set_property PACKAGE_PIN R2  [get_ports {iSw[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {iSw[*]}]

set_property PACKAGE_PIN U16 [get_ports {oLed[0]}]
set_property PACKAGE_PIN E19 [get_ports {oLed[1]}]
set_property PACKAGE_PIN U19 [get_ports {oLed[2]}]
set_property PACKAGE_PIN V19 [get_ports {oLed[3]}]
set_property PACKAGE_PIN W18 [get_ports {oLed[4]}]
set_property PACKAGE_PIN U15 [get_ports {oLed[5]}]
set_property PACKAGE_PIN U14 [get_ports {oLed[6]}]
set_property PACKAGE_PIN V14 [get_ports {oLed[7]}]
set_property PACKAGE_PIN V13 [get_ports {oLed[8]}]
set_property PACKAGE_PIN V3  [get_ports {oLed[9]}]
set_property PACKAGE_PIN W3  [get_ports {oLed[10]}]
set_property PACKAGE_PIN U3  [get_ports {oLed[11]}]
set_property PACKAGE_PIN P3  [get_ports {oLed[12]}]
set_property PACKAGE_PIN N3  [get_ports {oLed[13]}]
set_property PACKAGE_PIN P1  [get_ports {oLed[14]}]
set_property PACKAGE_PIN L1  [get_ports {oLed[15]}]
set_property IOSTANDARD LVCMOS33 [get_ports {oLed[*]}]

## PMOD JC wired to the master FPGA SPI pins.
set_property PACKAGE_PIN K17 [get_ports iSpiSclk]
set_property PACKAGE_PIN M18 [get_ports iSpiMosi]
set_property PACKAGE_PIN N17 [get_ports oSpiMiso]
set_property PACKAGE_PIN P18 [get_ports iSpiCsN]
set_property IOSTANDARD LVCMOS33 [get_ports {iSpiSclk iSpiMosi oSpiMiso iSpiCsN}]

set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]
